### ISSUE TITLE
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_'

### ISSUE THREAD

**Issue by csolisr** [rachmadaniHaryono/iqdb_tagger#14]
When attempting to run the default routine to identify pictures, the process fails immediately because of what seems to be an outdated library:

```
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/opt/venv/lib/python3.13/site-packages/urllib3/util/ssl_.py)
Traceback (most recent call last):
  File "/opt/venv/bin/iqdb-tagger", line 5, in <module>
    from iqdb_tagger.__main__ import cli
  File "/opt/venv/lib/python3.13/site-packages/iqdb_tagger/__main__.py", line 16, in <module>
    import cfscrape
  File "/opt/venv/lib/python3.13/site-packages/cfscrape/__init__.py", line 19, in <module>
    from urllib3.util.ssl_ import create_urllib3_context, DEFAULT_CIPHERS
```

**Comment by csolisr** [comment]
For now, the warning can be bypassed by downgrading `urllib3`:

```
pip3 install 'urllib3<2' --upgrade
```

**Comment by csolisr** [comment]
In related news, some of the functionality depends on `hydrus`, which itself depends on `greenlet<2.0` - problem being, that `greenlet` [no longer builds on Python 3.13 or above](https://github.com/python-greenlet/greenlet/pull/396) unless `greenlet` itself is updated to at least version `3.2.0`.

**Comment by csolisr** [comment]
I'm currently installing Python 3.10 in order to create a `venv` compatible with the latest version.

**Comment by csolisr** [comment]
Another problem: `hydrus` is not building because of `gevent==20.12.0` using a transitional `long` type.

```
[1/1] Cythonizing src/gevent/resolver/cares.pyx
      performance hint: src/gevent/libev/corecext.pyx:1307:0: Exception check on '_syserr_cb' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare '_syserr_cb' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on '_syserr_cb' to allow an error code to be returned.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef tuple integer_types
      
      if sys.version_info[0] >= 3:
          integer_types = int,
      else:
          integer_types = (int, long)
                                ^
      ------------------------------------------------------------
      
      src/gevent/libev/corecext.pyx:60:26: undeclared name not builtin: long
```
